
	CREATE TABLE IF NOT EXISTS USERS(
	    id bigint unique PRIMARY KEY NOT NULL,
	  username VARCHAR(250) NOT NULL,
	  password VARCHAR(250) NOT NULL,
	);
	
	
	
	CREATE TABLE IF NOT EXISTS CHECKITEM_TEMPLATE(
	  id VARCHAR(250) PRIMARY KEY NOT NULL
	  name VARCHAR(250) NOT NULL,
	  description VARCHAR(250),
	);