
	CREATE TABLE IF NOT EXISTS USERS(
	  username VARCHAR(250) PRIMARY KEY NOT NULL,
	  password VARCHAR(250)
	);
	
	
	
	CREATE TABLE IF NOT EXISTS CHECK_ITEM(
	  id VARCHAR(250) PRIMARY KEY NOT NULL
	);